#if !defined(AFX_BROWSEFOLDER_H__AF9F92E2_BFE4_11D3_9432_00104BF7274C__INCLUDED_)
#define AFX_BROWSEFOLDER_H__AF9F92E2_BFE4_11D3_9432_00104BF7274C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBrowseFolder wrapper class

class CBrowseFolder : public CWnd
{
protected:
	DECLARE_DYNCREATE(CBrowseFolder)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbd6d5970, 0x614a, 0x11d2, { 0x88, 0x3c, 0x82, 0x72, 0x9a, 0x77, 0xe7, 0xc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	long GetWindow();
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	long GetExpand();
	void SetExpand(long nNewValue);
	long GetRestorePreviousState();
	void SetRestorePreviousState(long nNewValue);
	CString GetSelectedFolderPath();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BROWSEFOLDER_H__AF9F92E2_BFE4_11D3_9432_00104BF7274C__INCLUDED_)
